name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj

      - name: Build the application
        run: dotnet build UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj --configuration Release --output ./artifacts

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Run unit tests
        run: dotnet test UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj --configuration Release --no-restore

      - name: Run code quality checks
        run: dotnet format UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj --check

  deploy:
    runs-on: windows-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Deploy to Staging
        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_Test }}
        run: |
          echo "Deploying to staging environment..."
          # Add your deployment commands here
